/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 10.1.111.135SPRINGMVC
Source Server Version : 110100
Source Host           : 10.1.111.135:1521
Source Schema         : SPRINGMVC

Target Server Type    : ORACLE
Target Server Version : 110100
File Encoding         : 65001

Date: 2018-03-19 10:53:36
*/


-- ----------------------------
-- Table structure for DEMO_TABLE
-- ----------------------------
DROP TABLE "SPRINGMVC"."DEMO_TABLE";
CREATE TABLE "SPRINGMVC"."DEMO_TABLE" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"COUNT_NUM" NUMBER NOT NULL ,
"CREATE_TIME" DATE NOT NULL ,
"UPDATE_TIME" DATE NOT NULL ,
"CUSTOM_TIME" DATE NOT NULL ,
"CUSTOM_TIME_STR" VARCHAR2(14 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for LOG_RECORD
-- ----------------------------
DROP TABLE "SPRINGMVC"."LOG_RECORD";
CREATE TABLE "SPRINGMVC"."LOG_RECORD" (
"LOG_ID" VARCHAR2(100 BYTE) NOT NULL ,
"OPERATION_START_TIME" DATE NULL ,
"OPERATION_END_TIME" DATE NULL ,
"OPERATION_ELAPSED_TIME_MILLIS" NUMBER(32) NULL ,
"OPERATION_TYPE" VARCHAR2(255 BYTE) NULL ,
"OPERATION_DESC" VARCHAR2(255 BYTE) NULL ,
"OPERATION_USERNAME" VARCHAR2(100 BYTE) NULL ,
"OPERATION_USER_ID" VARCHAR2(100 BYTE) NULL ,
"TARGET_CLASS" VARCHAR2(255 BYTE) NULL ,
"TARGET_METHOD" VARCHAR2(255 BYTE) NULL ,
"TARGET_METHOD_RESULT" VARCHAR2(2000 BYTE) NULL ,
"TARGET_METHOD_EXCEPTION" VARCHAR2(2000 BYTE) NULL ,
"TARGET_METHOD_PARAMS" VARCHAR2(2000 BYTE) NULL ,
"POINTCUT_METHOD_NAME" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for PERSISTENT_LOGINS
-- ----------------------------
DROP TABLE "SPRINGMVC"."PERSISTENT_LOGINS";
CREATE TABLE "SPRINGMVC"."PERSISTENT_LOGINS" (
"USERNAME" VARCHAR2(64 BYTE) NULL ,
"SERIES" VARCHAR2(64 BYTE) NOT NULL ,
"TOKEN" VARCHAR2(64 BYTE) NULL ,
"LAST_USED" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SPRINGMVC"."PERSISTENT_LOGINS" IS 'Spring Remember me 持久化';

-- ----------------------------
-- Table structure for QRTZ_BLOB_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"BLOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_CALENDARS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_CALENDARS";
CREATE TABLE "SPRINGMVC"."QRTZ_CALENDARS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"CALENDAR" BLOB NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_CRON_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"CRON_EXPRESSION" VARCHAR2(120 BYTE) NOT NULL ,
"TIME_ZONE_ID" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_FIRED_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"ENTRY_ID" VARCHAR2(95 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"FIRED_TIME" NUMBER(13) NOT NULL ,
"PRIORITY" NUMBER(13) NOT NULL ,
"STATE" VARCHAR2(16 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_JOB_DETAILS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS";
CREATE TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"JOB_CLASS_NAME" VARCHAR2(250 BYTE) NOT NULL ,
"IS_DURABLE" VARCHAR2(1 BYTE) NOT NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NOT NULL ,
"IS_UPDATE_DATA" VARCHAR2(1 BYTE) NOT NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NOT NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_LOCKS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_LOCKS";
CREATE TABLE "SPRINGMVC"."QRTZ_LOCKS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"LOCK_NAME" VARCHAR2(40 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_PAUSED_TRIGGER_GRPS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_PAUSED_TRIGGER_GRPS";
CREATE TABLE "SPRINGMVC"."QRTZ_PAUSED_TRIGGER_GRPS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_SCHEDULER_STATE
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE";
CREATE TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"LAST_CHECKIN_TIME" NUMBER(13) NOT NULL ,
"CHECKIN_INTERVAL" NUMBER(13) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_SIMPLE_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"REPEAT_COUNT" NUMBER(7) NOT NULL ,
"REPEAT_INTERVAL" NUMBER(12) NOT NULL ,
"TIMES_TRIGGERED" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_SIMPROP_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"STR_PROP_1" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_2" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_3" VARCHAR2(512 BYTE) NULL ,
"INT_PROP_1" NUMBER(10) NULL ,
"INT_PROP_2" NUMBER(10) NULL ,
"LONG_PROP_1" NUMBER(13) NULL ,
"LONG_PROP_2" NUMBER(13) NULL ,
"DEC_PROP_1" NUMBER(13,4) NULL ,
"DEC_PROP_2" NUMBER(13,4) NULL ,
"BOOL_PROP_1" VARCHAR2(1 BYTE) NULL ,
"BOOL_PROP_2" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for QRTZ_TRIGGERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."QRTZ_TRIGGERS";
CREATE TABLE "SPRINGMVC"."QRTZ_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"NEXT_FIRE_TIME" NUMBER(13) NULL ,
"PREV_FIRE_TIME" NUMBER(13) NULL ,
"PRIORITY" NUMBER(13) NULL ,
"TRIGGER_STATE" VARCHAR2(16 BYTE) NOT NULL ,
"TRIGGER_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"START_TIME" NUMBER(13) NOT NULL ,
"END_TIME" NUMBER(13) NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NULL ,
"MISFIRE_INSTR" NUMBER(2) NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_AUTHORITIES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_AUTHORITIES";
CREATE TABLE "SPRINGMVC"."SYS_AUTHORITIES" (
"AUTHORITY_ID" VARCHAR2(100 BYTE) NOT NULL ,
"AUTHORITY_MARK" VARCHAR2(100 BYTE) NULL ,
"AUTHORITY_NAME" VARCHAR2(100 BYTE) NOT NULL ,
"AUTHORITY_DESC" VARCHAR2(200 BYTE) NULL ,
"MESSAGE" VARCHAR2(100 BYTE) NULL ,
"ENABLE" NUMBER NULL ,
"ISSYS" NUMBER NULL ,
"MODULE_ID" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_AUTHORITIES_RESOURCES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES";
CREATE TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"RESOURCE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"AUTHORITY_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_MODULES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_MODULES";
CREATE TABLE "SPRINGMVC"."SYS_MODULES" (
"MODULE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"MODULE_NAME" VARCHAR2(100 BYTE) NOT NULL ,
"MODULE_DESC" VARCHAR2(200 BYTE) NULL ,
"MODULE_TYPE" VARCHAR2(100 BYTE) NULL ,
"PARENT" VARCHAR2(100 BYTE) NULL ,
"MODULE_URL" VARCHAR2(100 BYTE) NULL ,
"I_LEVEL" NUMBER NULL ,
"LEAF" NUMBER NULL ,
"APPLICATION" VARCHAR2(100 BYTE) NULL ,
"CONTROLLER" VARCHAR2(100 BYTE) NULL ,
"ENABLE" NUMBER(1) NULL ,
"PRIORITY" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "SPRINGMVC"."SYS_MODULES"."I_LEVEL" IS '1';

-- ----------------------------
-- Table structure for SYS_RESOURCES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_RESOURCES";
CREATE TABLE "SPRINGMVC"."SYS_RESOURCES" (
"RESOURCE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"RESOURCE_TYPE" VARCHAR2(100 BYTE) NULL ,
"RESOURCE_NAME" VARCHAR2(100 BYTE) NULL ,
"RESOURCE_DESC" VARCHAR2(200 BYTE) NULL ,
"RESOURCE_PATH" VARCHAR2(200 BYTE) NULL ,
"PRIORITY" VARCHAR2(100 BYTE) NULL ,
"ENABLE" NUMBER NULL ,
"ISSYS" NUMBER NULL ,
"MODULE_ID" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "SPRINGMVC"."SYS_RESOURCES"."RESOURCE_TYPE" IS 'URL,METHOD';

-- ----------------------------
-- Table structure for SYS_ROLES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_ROLES";
CREATE TABLE "SPRINGMVC"."SYS_ROLES" (
"ROLE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"ROLE_NAME" VARCHAR2(100 BYTE) NULL ,
"ROLE_DESC" VARCHAR2(200 BYTE) NULL ,
"ENABLE" NUMBER NULL ,
"ISSYS" NUMBER NULL ,
"MODULE_ID" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_ROLES_AUTHORITIES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES";
CREATE TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"AUTHORITY_ID" VARCHAR2(100 BYTE) NOT NULL ,
"ROLE_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_ROLES_MODULES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_ROLES_MODULES";
CREATE TABLE "SPRINGMVC"."SYS_ROLES_MODULES" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"MODULE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"ROLE_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SPRINGMVC"."SYS_ROLES_MODULES" IS '控制角色对模块的访问权，主要用于生成菜单';

-- ----------------------------
-- Table structure for SYS_USERS
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_USERS";
CREATE TABLE "SPRINGMVC"."SYS_USERS" (
"USER_ID" VARCHAR2(100 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(100 BYTE) NOT NULL ,
"NAME" VARCHAR2(100 BYTE) NULL ,
"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ,
"DT_CREATE" DATE DEFAULT SYSDATE  NULL ,
"LAST_LOGIN" DATE NULL ,
"DEADLINE" DATE NULL ,
"LOGIN_IP" VARCHAR2(100 BYTE) NULL ,
"V_QZJGID" VARCHAR2(100 BYTE) NULL ,
"V_QZJGMC" VARCHAR2(100 BYTE) NULL ,
"DEP_ID" VARCHAR2(100 BYTE) NULL ,
"DEP_NAME" VARCHAR2(100 BYTE) NULL ,
"ENABLED" NUMBER NULL ,
"ACCOUNT_NON_EXPIRED" NUMBER NULL ,
"ACCOUNT_NON_LOCKED" NUMBER NULL ,
"CREDENTIALS_NON_EXPIRED" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for SYS_USERS_ROLES
-- ----------------------------
DROP TABLE "SPRINGMVC"."SYS_USERS_ROLES";
CREATE TABLE "SPRINGMVC"."SYS_USERS_ROLES" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"ROLE_ID" VARCHAR2(100 BYTE) NOT NULL ,
"USER_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for WELCOME
-- ----------------------------
DROP TABLE "SPRINGMVC"."WELCOME";
CREATE TABLE "SPRINGMVC"."WELCOME" (
"ID" VARCHAR2(64 BYTE) NOT NULL ,
"USER_ID" VARCHAR2(64 BYTE) NULL ,
"USER_NAME" VARCHAR2(64 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table DEMO_TABLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table DEMO_TABLE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DEMO_TABLE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table LOG_RECORD
-- ----------------------------

-- ----------------------------
-- Checks structure for table LOG_RECORD
-- ----------------------------
ALTER TABLE "SPRINGMVC"."LOG_RECORD" ADD CHECK ("LOG_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."LOG_RECORD" ADD CHECK ("LOG_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."LOG_RECORD" ADD CHECK ("LOG_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."LOG_RECORD" ADD CHECK ("LOG_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table LOG_RECORD
-- ----------------------------
ALTER TABLE "SPRINGMVC"."LOG_RECORD" ADD PRIMARY KEY ("LOG_ID");

-- ----------------------------
-- Indexes structure for table PERSISTENT_LOGINS
-- ----------------------------

-- ----------------------------
-- Checks structure for table PERSISTENT_LOGINS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."PERSISTENT_LOGINS" ADD CHECK ("SERIES" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."PERSISTENT_LOGINS" ADD CHECK ("SERIES" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PERSISTENT_LOGINS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."PERSISTENT_LOGINS" ADD PRIMARY KEY ("SERIES");

-- ----------------------------
-- Indexes structure for table QRTZ_BLOB_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_CALENDARS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_CALENDARS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_CALENDARS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_CALENDARS" ADD CHECK ("CALENDAR_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_CALENDARS" ADD CHECK ("CALENDAR" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_CALENDARS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_CALENDARS" ADD PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME");

-- ----------------------------
-- Indexes structure for table QRTZ_CRON_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD CHECK ("CRON_EXPRESSION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_FIRED_TRIGGERS
-- ----------------------------
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_INST_JOB_REQ_RCVRY"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "INSTANCE_NAME" ASC, "REQUESTS_RECOVERY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_JG"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_J_G"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "JOB_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_TG"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_TRIG_INST_NAME"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "INSTANCE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_FT_T_G"
ON "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table QRTZ_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("ENTRY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("FIRED_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("PRIORITY" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD CHECK ("STATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_FIRED_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "ENTRY_ID");

-- ----------------------------
-- Indexes structure for table QRTZ_JOB_DETAILS
-- ----------------------------
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_J_GRP"
ON "SPRINGMVC"."QRTZ_JOB_DETAILS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_J_REQ_RECOVERY"
ON "SPRINGMVC"."QRTZ_JOB_DETAILS" ("SCHED_NAME" ASC, "REQUESTS_RECOVERY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table QRTZ_JOB_DETAILS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("JOB_CLASS_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("IS_DURABLE" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("IS_NONCONCURRENT" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("IS_UPDATE_DATA" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD CHECK ("REQUESTS_RECOVERY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_JOB_DETAILS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_JOB_DETAILS" ADD PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_LOCKS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_LOCKS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_LOCKS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_LOCKS" ADD CHECK ("LOCK_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_LOCKS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_LOCKS" ADD PRIMARY KEY ("SCHED_NAME", "LOCK_NAME");

-- ----------------------------
-- Indexes structure for table QRTZ_PAUSED_TRIGGER_GRPS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_PAUSED_TRIGGER_GRPS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_PAUSED_TRIGGER_GRPS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_PAUSED_TRIGGER_GRPS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_SCHEDULER_STATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" ADD CHECK ("LAST_CHECKIN_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" ADD CHECK ("CHECKIN_INTERVAL" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SCHEDULER_STATE" ADD PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME");

-- ----------------------------
-- Indexes structure for table QRTZ_SIMPLE_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_COUNT" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_INTERVAL" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD CHECK ("TIMES_TRIGGERED" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_SIMPROP_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QRTZ_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table QRTZ_TRIGGERS
-- ----------------------------
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_C"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "CALENDAR_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_G"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_J"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "JOB_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_JG"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_NEXT_FIRE_TIME"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_NFT_MISFIRE"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_NFT_ST"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_STATE" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_NFT_ST_MISFIRE"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_NFT_ST_MISFIRE_GRP"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_N_G_STATE"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_N_STATE"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_NAME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SPRINGMVC"."IDX_QRTZ_T_STATE"
ON "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table QRTZ_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("TRIGGER_STATE" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("TRIGGER_TYPE" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD CHECK ("START_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QRTZ_TRIGGERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table SYS_AUTHORITIES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_AUTHORITIES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES" ADD CHECK ("AUTHORITY_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES" ADD CHECK ("AUTHORITY_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_AUTHORITIES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES" ADD PRIMARY KEY ("AUTHORITY_ID");

-- ----------------------------
-- Indexes structure for table SYS_AUTHORITIES_RESOURCES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_AUTHORITIES_RESOURCES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("RESOURCE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("RESOURCE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_AUTHORITIES_RESOURCES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_MODULES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_MODULES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_MODULES" ADD CHECK ("MODULE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_MODULES" ADD CHECK ("MODULE_NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_MODULES" ADD CHECK ("MODULE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_MODULES" ADD CHECK ("MODULE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_MODULES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_MODULES" ADD PRIMARY KEY ("MODULE_ID");

-- ----------------------------
-- Indexes structure for table SYS_RESOURCES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_RESOURCES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_RESOURCES" ADD CHECK ("RESOURCE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_RESOURCES" ADD CHECK ("RESOURCE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_RESOURCES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_RESOURCES" ADD PRIMARY KEY ("RESOURCE_ID");

-- ----------------------------
-- Indexes structure for table SYS_ROLES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ROLES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES" ADD CHECK ("ROLE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ROLES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES" ADD PRIMARY KEY ("ROLE_ID");

-- ----------------------------
-- Indexes structure for table SYS_ROLES_AUTHORITIES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ROLES_AUTHORITIES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("AUTHORITY_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD CHECK ("ROLE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ROLES_AUTHORITIES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_ROLES_MODULES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ROLES_MODULES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("MODULE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("MODULE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD CHECK ("ROLE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ROLES_MODULES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_USERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_USERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD CHECK ("PASSWORD" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_USERS
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_USERS" ADD PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Indexes structure for table SYS_USERS_ROLES
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_USERS_ROLES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD CHECK ("USER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_USERS_ROLES
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table WELCOME
-- ----------------------------

-- ----------------------------
-- Checks structure for table WELCOME
-- ----------------------------
ALTER TABLE "SPRINGMVC"."WELCOME" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."WELCOME" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."WELCOME" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table WELCOME
-- ----------------------------
ALTER TABLE "SPRINGMVC"."WELCOME" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."QRTZ_BLOB_TRIGGERS"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_BLOB_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."QRTZ_CRON_TRIGGERS"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_CRON_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPLE_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_SIMPROP_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "SPRINGMVC"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."QRTZ_TRIGGERS"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."QRTZ_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "SPRINGMVC"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD FOREIGN KEY ("AUTHORITY_ID") REFERENCES "SPRINGMVC"."SYS_AUTHORITIES" ("AUTHORITY_ID");
ALTER TABLE "SPRINGMVC"."SYS_AUTHORITIES_RESOURCES" ADD FOREIGN KEY ("RESOURCE_ID") REFERENCES "SPRINGMVC"."SYS_RESOURCES" ("RESOURCE_ID");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."SYS_RESOURCES"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_RESOURCES" ADD FOREIGN KEY ("MODULE_ID") REFERENCES "SPRINGMVC"."SYS_MODULES" ("MODULE_ID");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."SYS_ROLES_AUTHORITIES"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD FOREIGN KEY ("AUTHORITY_ID") REFERENCES "SPRINGMVC"."SYS_AUTHORITIES" ("AUTHORITY_ID");
ALTER TABLE "SPRINGMVC"."SYS_ROLES_AUTHORITIES" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "SPRINGMVC"."SYS_ROLES" ("ROLE_ID");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."SYS_ROLES_MODULES"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD FOREIGN KEY ("MODULE_ID") REFERENCES "SPRINGMVC"."SYS_MODULES" ("MODULE_ID");
ALTER TABLE "SPRINGMVC"."SYS_ROLES_MODULES" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "SPRINGMVC"."SYS_ROLES" ("ROLE_ID");

-- ----------------------------
-- Foreign Key structure for table "SPRINGMVC"."SYS_USERS_ROLES"
-- ----------------------------
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "SPRINGMVC"."SYS_ROLES" ("ROLE_ID");
ALTER TABLE "SPRINGMVC"."SYS_USERS_ROLES" ADD FOREIGN KEY ("USER_ID") REFERENCES "SPRINGMVC"."SYS_USERS" ("USER_ID");
