/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 10.1.111.135SPRINGMVC
Source Server Version : 110100
Source Host           : 10.1.111.135:1521
Source Schema         : SPRINGMVC

Target Server Type    : ORACLE
Target Server Version : 110100
File Encoding         : 65001

Date: 2018-03-19 10:53:13
*/


-- ----------------------------
-- Table structure for DEMO_TABLE
-- ----------------------------
DROP TABLE "SPRINGMVC"."DEMO_TABLE";
CREATE TABLE "SPRINGMVC"."DEMO_TABLE" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"COUNT_NUM" NUMBER NOT NULL ,
"CREATE_TIME" DATE NOT NULL ,
"UPDATE_TIME" DATE NOT NULL ,
"CUSTOM_TIME" DATE NOT NULL ,
"CUSTOM_TIME_STR" VARCHAR2(14 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table DEMO_TABLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table DEMO_TABLE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("COUNT_NUM" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD CHECK ("CUSTOM_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DEMO_TABLE
-- ----------------------------
ALTER TABLE "SPRINGMVC"."DEMO_TABLE" ADD PRIMARY KEY ("ID");
